export type numberOrNull = number | null;
export type stringOrNull = string | null;
export type ReportModel = {
  date: string;
  adultIntensiveCareRatio: string;
  fillationRatio: string;
  pneumoniaPercent: string;
  ventilatorOccupancyRatio: string;
  bedOccupancyRate: string;
  totalTests: string;
  totalPatients: string;
  totalDeaths: string;
  totalIntensiveCare: string;
  totalIntubated: string;
  totalRecovered: string;
  tests: string;
  cases: string;
  patients: string;
  critical: string;
  deaths: string;
  recovered: string;
};
